# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd
import numpy as np

In [15]:
# your code here
tici = pd.read_csv(r"C:\Users\leube\Ironhack\cloned_labs\module_3\Lab_13_Deep-Learning\tic-tac-toe.csv")
tici
# true --> player x wins
# false --> player o wins or draw

    TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [3]:
for x in list(tici.columns):
    print(x)
    print(tici[x].unique())
    print('\n')

TL
['x' 'o' 'b']


TM
['x' 'o' 'b']


TR
['x' 'o' 'b']


ML
['x' 'o' 'b']


MM
['o' 'b' 'x']


MR
['o' 'b' 'x']


BL
['x' 'o' 'b']


BM
['o' 'x' 'b']


BR
['o' 'x' 'b']


class
[ True False]

In [8]:
list(tici.columns)[:-1]

['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR']

In [16]:
for x in list(tici.columns)[:-1]:
    tici.loc[tici[tici[x]=='x'].index, x] = 0
    tici.loc[tici[tici[x]=='o'].index, x] = 1
    tici.loc[tici[tici[x]=='b'].index, x] = 2

In [17]:
for x in list(tici.columns):
    print(x)
    print(tici[x].unique())
    print('\n')

TL
[0 1 2]


TM
[0 1 2]


TR
[0 1 2]


ML
[0 1 2]


MM
[1 2 0]


MR
[1 2 0]


BL
[0 1 2]


BM
[1 0 2]


BR
[1 0 2]


class
[ True False]

In [18]:
tici['class'] = np.where(tici['class']==True,1,0)

In [19]:
X = tici.drop('class',axis=1)
y = tici['class']

In [20]:
# normalize data, per column or per row?
Xtr = X.transpose()
Xtr

,0,1,2,3,4,5,6,7,8,9,...,948,949,950,951,952,953,954,955,956,957
TL,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,1
TM,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,1
TR,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,1,1,0
ML,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,1,0
MM,1,1,1,1,1,1,1,1,1,2,...,0,1,0,0,1,1,0,1,0,0
MR,1,1,1,1,1,1,2,2,2,1,...,0,0,0,1,1,1,1,0,0,1
BL,0,1,1,1,2,2,1,1,2,1,...,1,0,0,1,0,1,0,0,0,1
BM,1,0,1,2,1,2,1,2,1,1,...,0,0,0,1,1,0,1,1,1,0
BR,1,1,0,2,2,1,2,1,1,2,...,1,1,1,0,0,0,0,0,0,0

In [21]:
for x in list(Xtr.columns):
    mini = Xtr[x].min()
    maxi = Xtr[x].max()
    Xtr[x] = (Xtr[x]-mini)/(maxi-mini)

In [25]:
# finished noralized data (row wise)

X = Xtr.transpose()

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [53]:
# your code here
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [56]:
X_train = np.asarray(X_train).astype(np.float32)

In [55]:
y_train = np.asarray(y_train).astype(np.float32)

In [62]:
X_test = np.asarray(X_test).astype(np.float32)

In [63]:
y_test = np.asarray(y_test).astype(np.float32)

In [34]:
import tensorflow as tf

In [60]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])
model.fit(X_train,y_train, epochs=9)

Epoch 1/9
24/24 [==============================] - 1s 3ms/step - loss: 0.6274 - accuracy: 0.6462
Epoch 2/9
24/24 [==============================] - 0s 3ms/step - loss: 0.5771 - accuracy: 0.6815
Epoch 3/9
24/24 [==============================] - 0s 3ms/step - loss: 0.4602 - accuracy: 0.7990
Epoch 4/9
24/24 [==============================] - 0s 3ms/step - loss: 0.3044 - accuracy: 0.8864
Epoch 5/9
24/24 [==============================] - 0s 3ms/step - loss: 0.1979 - accuracy: 0.9151
Epoch 6/9
24/24 [==============================] - 0s 4ms/step - loss: 0.0948 - accuracy: 0.9713
Epoch 7/9
24/24 [==============================] - 0s 4ms/step - loss: 0.0593 - accuracy: 0.9856
Epoch 8/9
24/24 [==============================] - 0s 4ms/step - loss: 0.0421 - accuracy: 0.9883
Epoch 9/9
24/24 [==============================] - 0s 4ms/step - loss: 0.0295 - accuracy: 0.9922

In [65]:
model.save('tic_tac_toe.model')

INFO:tensorflow:Assets written to: tic_tac_toe.model\assets

In [66]:
new_model = tf.keras.models.load_model('tic_tac_toe.model')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [ ]:
# your code here

In [64]:
val_loss, val_acc = model.evaluate(X_test, y_test)

6/6 [==============================] - 3s 4ms/step - loss: 0.0837 - accuracy: 0.9635

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here
# model has sufficient enough results, due to multiple epochs and multiple hidden layers

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here