In [1]:
# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [4]:
data = pd.read_csv(r"C:\Users\leube\Downloads\movie_metadata.csv")
movies = pd.DataFrame(data)

In [7]:
movies.reset_index(inplace=True)

In [8]:
movies

,index,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [6]:
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

### 2. Use crosstabs to show the number of moovies per country

In [15]:
pd.crosstab(movies.country, movies.index)
pd.crosstab(movies.country,movies.country, values=movies.index, aggfunc='count').round(0).fillna(0)

# why would I do this with a crosstab?? no column column needed

country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Argentina,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aruba,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Australia,0.0,0.0,0.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bahamas,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Turkey,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
UK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,448.0,0.0,0.0,0.0
USA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3807.0,0.0,0.0
United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
West Germany,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [16]:
movies

,index,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [18]:
# pd.crosstab(df.make, [df.body_style, df.drive_wheels])

pd.crosstab(movies.director_name, [movies.country, movies.genres])

country            Afghanistan            Argentina        \
genres                   Drama Crime|Drama|Thriller Drama
director_name
A. Raven Cruz                0                    0     0
Aaron Hann                   0                    0     0
Aaron Schneider              0                    0     0
Aaron Seltzer                0                    0     0
Abel Ferrara                 0                    0     0
...                        ...                  ...   ...
Zoran Lisinac                0                    0     0
Álex de la Iglesia           0                    0     0
Émile Gaudreault             0                    0     0
Éric Tessier                 0                    0     0
Étienne Faure                0                    0     0

country                                                    Aruba  \
genres             Drama|Mystery|Thriller Action|Comedy|Thriller
director_name
A. Raven Cruz                           0                      0
Aaron Hann                              0                      0
Aaron Schneider                         0                      0
Aaron Seltzer                           0                      0
Abel Ferrara                            0                      0
...                                   ...                    ...
Zoran Lisinac                           0                      0
Álex de la Iglesia                      0                      0
Émile Gaudreault                        0                      0
Éric Tessier                            0                      0
Étienne Faure                           0                      0

country                                                   Australia  \
genres             Action|Adventure|Animation|Comedy|Family|Fantasy
director_name
A. Raven Cruz                                                     0
Aaron Hann                                                        0
Aaron Schneider                                                   0
Aaron Seltzer                                                     0
Abel Ferrara                                                      0
...                                                             ...
Zoran Lisinac                                                     0
Álex de la Iglesia                                                0
Émile Gaudreault                                                  0
Éric Tessier                                                      0
Étienne Faure                                                     0

country                                                                    \
genres             Action|Adventure|Comedy Action|Adventure|Comedy|Family
director_name
A. Raven Cruz                            0                              0
Aaron Hann                               0                              0
Aaron Schneider                          0                              0
Aaron Seltzer                            0                              0
Abel Ferrara                             0                              0
...                                    ...                            ...
Zoran Lisinac                            0                              0
Álex de la Iglesia                       0                              0
Émile Gaudreault                         0                              0
Éric Tessier                             0                              0
Étienne Faure                            0                              0

country                                             \
genres             Action|Adventure|Comedy|Fantasy
director_name
A. Raven Cruz                                    0
Aaron Hann                                       0
Aaron Schneider                                  0
Aaron Seltzer                                    0
Abel Ferrara                                     0
...                                            ...
Zoran Lisinac                                    0
Álex de la Iglesia                               0
Émile Gaudreault                                 0
Éric Tessier                                     0
Étienne Faure                                    0

country                                                    ...           USA  \
genres             Action|Adventure|Drama|Romance|Western  ... Romance|Short
director_name                                              ...
A. Raven Cruz                                           0  ...             0
Aaron Hann                                              0  ...             0
Aaron Schneider                                         0  ...             0
Aaron Seltzer                                           0  ...             0
Abel Ferrara                                            0  ...             0
...                                                   ...  ...           ...
Zoran Lisinac                                           0  ...             0
Álex de la Iglesia                                      0  ...             0
Émile Gaudreault                                        0  ...             0
Éric Tessier                                            0  ...             0
Étienne Faure                                           0  ...             0

country                                                                      \
genres             Sci-Fi Sci-Fi|Thriller Thriller Thriller|Western Western
director_name
A. Raven Cruz           0               0        0                0       0
Aaron Hann              0               0        0                0       0
Aaron Schneider         0               0        0                0       0
Aaron Seltzer           0               0        0                0       0
Abel Ferrara            0               0        0                0       0
...                   ...             ...      ...              ...     ...
Zoran Lisinac           0               0        0                0       0
Álex de la Iglesia      0               0        0                0       0
Émile Gaudreault        0               0        0                0       0
Éric Tessier            0               0        0                0       0
Étienne Faure           0               0        0                0       0

country            United Arab Emirates                   West Germany  \
genres               Documentary|Family Adventure|Drama|Family|Fantasy
director_name
A. Raven Cruz                         0                              0
Aaron Hann                            0                              0
Aaron Schneider                       0                              0
Aaron Seltzer                         0                              0
Abel Ferrara                          0                              0
...                                 ...                            ...
Zoran Lisinac                         0                              0
Álex de la Iglesia                    0                              0
Émile Gaudreault                      0                              0
Éric Tessier                          0                              0
Étienne Faure                         0                              0

country
genres             Adventure|Drama|Thriller|War Horror|Mystery
director_name
A. Raven Cruz                                 0              0
Aaron Hann                                    0              0
Aaron Schneider                               0              0
Aaron Seltzer                                 0              0
Abel Ferrara                                  0              0
...                                         ...            ...
Zoran Lisinac                                 0              0
Álex de la Iglesia                            0              0
Émile Gaudreault                              0              0
Éric Tessier                                  0              0
Étienne Faure                                 0              0

[2395 rows x 1548 columns]

### 4. Average duration of filmes grouped by color

In [19]:
pd.crosstab(movies.color, movies.duration)

duration,7.0,11.0,14.0,20.0,22.0,23.0,24.0,25.0,27.0,28.0,...,271.0,280.0,286.0,289.0,293.0,300.0,325.0,330.0,334.0,511.0
color,,,,,,,,,,,,,,,,,,,,,
Black and White,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Color,2,1,1,1,6,2,2,3,1,1,...,1,1,1,1,1,1,1,1,1,1

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [20]:
movies.columns

Index(['index', 'color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [25]:
# pd.crosstab([df.make, df.num_doors], [df.body_style, df.drive_wheels],
         #   rownames=['Auto Manufacturer', "Doors"],
         #   colnames=['Body Style', "Drive Type"],
         #   dropna=False)
            
# way to rename rows and columns, indicate to not drop missing values

pd.crosstab(movies.director_name, movies.director_name, values=movies.actor_1_facebook_likes, aggfunc='sum').round(0).fillna(0)

director_name,A. Raven Cruz,Aaron Hann,Aaron Schneider,Aaron Seltzer,Abel Ferrara,Adam Brooks,Adam Carolla,Adam Goldberg,Adam Green,Adam Jay Epstein,...,Zack Snyder,Zack Ward,Zackary Adler,Zak Penn,Zal Batmanglij,Zoran Lisinac,Álex de la Iglesia,Émile Gaudreault,Éric Tessier,Étienne Faure
director_name,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,639.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aaron Hann,0.0,160.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aaron Schneider,0.0,0.0,13000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aaron Seltzer,0.0,0.0,0.0,3000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Abel Ferrara,0.0,0.0,0.0,0.0,812.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoran Lisinac,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,431.0,0.0,0.0,0.0,0.0
Álex de la Iglesia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,439.0,0.0,0.0,0.0
Émile Gaudreault,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,636.0,0.0,0.0
Éric Tessier,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0
Étienne Faure,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0

In [22]:
# why on earth use a crosstab here???

movies.groupby(by='director_name').agg({'actor_1_facebook_likes':'sum'})

                    actor_1_facebook_likes
director_name
A. Raven Cruz                        639.0
Aaron Hann                           160.0
Aaron Schneider                    13000.0
Aaron Seltzer                       3000.0
Abel Ferrara                         812.0
...                                    ...
Zoran Lisinac                        431.0
Álex de la Iglesia                   439.0
Émile Gaudreault                     636.0
Éric Tessier                          50.0
Étienne Faure                         19.0

[2398 rows x 1 columns]